name: TDRPlaytime
version: ${project.version}
main: nl.thedutchruben.playtime.Playtime
api-version: 1.16
authors: [TheDutchRuben]
description: Playtime plugin
commands:
  playtime:
    aliases:
      - ptime
      - playertime
      - onlinetime
    description: Main play time command
    permission: playtime.playtime
permissions:
  playtime.playtime:
    default: true
  playtime.playtime.other:
    default: op
  playtime.playtime.reset:
    default: op
